set access token through it's method maybe tedious
tweepy/tweepy pull request #1158
Opened 2019-01-21 11:48 UTC by orekiHoutarou

Because the only method that would influence the OAuthHandler instance's access token is set_access_token, adding a shortcut that set the access token in intantialization would be more user-friendly ? (as far as I'm concerned)
It is just a small modification, thanks for your patience on reading this comments...

2020-05-10 13:25 UTC, MichaelCurrin commented
The change looks good to me. 

Though the fork repo has been deleted.

Also curious as to why the `.encode` is applied to consumer tokens and not access tokens even in the original flow (in `.set_access_token`). No maybe its no needed, or it should be added to `__init__` for the access tokens for consistency.

2021-01-24 11:18 UTC, Harmon758 requested changes
There are conflicts that need to be resolved now.

2021-01-24 11:18 UTC, Harmon758 commented on tweepy/auth.py
> +    def __init__(self, consumer_key, consumer_secret, callback=None, access_token=None, access_token_secret=None):
```suggestion
    def __init__(self, consumer_key, consumer_secret, access_token=None,
                 access_token_secret=None, callback=None):
```

2022-01-08 00:49 UTC, Harmon758 commented
Superseded by https://github.com/tweepy/tweepy/commit/99f3583d99ac9a0003273318e7628235bba707f0

2022-01-08 00:49 UTC, closed without merging