Fix help() calls on the instantiated API, by remove confusing propert…
tweepy/tweepy pull request #1211
Opened 2019-05-07 18:08 UTC by johnkw

…y decorators from some of the member functions, which are not actually property descriptors.

Consolidate function docs for legacy _lookup_users() _lookup_users() functions, which can now be removed given the way bind_api has been used since 2014, which also improves help() for them.

This also makes the nature of pagination more obvious and explicit.

2019-05-16 15:46 UTC, okomarov commented
It was unclear what you meant by improved `help()`:

BEFORE
```python
help(tweepy.api.home_timeline)

Help on function _call in module tweepy.binder:

_call(*args, **kwargs)
```

AFTER
```python
help(tweepy.api.home_timeline)

Help on method home_timeline in module tweepy.api:

home_timeline(*args, **kwargs) method of tweepy.api.API instance
    :reference: https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline
    :allowed_param:'since_id', 'max_id', 'count'
```

This is nice, +1. 

However, you have the pagination settings in API and I think @joshthecoder (@Harmon758) intended to keep that file as close as possible to the twitter API, i.e. just as a simple mapping.

2019-05-16 16:35 UTC, johnkw commented
> However, you have the pagination settings in API and I think @joshthecoder (@Harmon758) intended to keep that file as close as possible to the twitter API, i.e. just as a simple mapping.

The paging style has always been stored in api.py, it's just that previously the "cursor" information was guessed at with some unusual logic in the binder.py file.  At least now it's more obvious what's going on, and the code is simpler.

I merged the fork so the pull request should be ready to commit again.

2019-05-16 16:47 UTC, okomarov commented
It is more obvious but this way the twitter api becomes polluted with tweepy internals. The Twitter API uses `max_id`, `since_id`, `cursor` and `page` while `pagination_mode` is tweepy only.

The correct way would be to keep the separation between `api.py` and tweepy internals. Remove pagination_mode altogether and let the tweepy Cursor do the heavy lifting/guessing with max_id`, `since_id`, `cursor` and `page`.

2019-05-16 17:01 UTC, johnkw commented
Yes, as I alluded to in issue #1212 it would be good to clean up api.py so that the function definition isn't the place that pagination_mode has to be stored. My plan was to create a patch that dynamically generates the API member functions in api.py from a dict().  This would get rid of all the boiler-plate bind_api repetition that makes api.py hard to read. The Cursor code would be able to access that same dict() to get the pagination style. In any case, one cleanup at a time. If the project is still active and accepting patches I'll keep going.

2021-01-11 19:46 UTC, Harmon758 requested changes
This should make use of the pagination decorator added with https://github.com/tweepy/tweepy/commit/cb3f22af66ddf9ddca3b57ff0d6d24a51902ff42.

There's also conflicts that need to be resolved now.

2021-01-11 19:46 UTC, Harmon758 commented on tweepy/api.py
> +    def me(self, *args, **kwargs):
I don't think this is necessary.

2021-01-11 19:46 UTC, Harmon758 commented on tweepy/api.py
>      def mutes(self):
```suggestion
    def mutes(self, *args, **kwargs):
```

2021-01-11 19:46 UTC, Harmon758 commented on tweepy/api.py
>          )
```suggestion
        )(*args, **kwargs)
```

2021-01-28 16:30 UTC, Harmon758 commented
This should now be resolved with https://github.com/tweepy/tweepy/commit/ab02eb532018dd2b0043c990cd2b3c12fb9ca6df.

2021-01-28 16:30 UTC, closed without merging