make User object hashable to allow use with sets
tweepy/tweepy pull request #1306
Opened 2019-12-24 03:19 UTC by mef51

this allows creating sets out of the results of queries and enables useful set operations and one-liners like 
```connections = list(set(followers) & set(friends))```

2020-12-30 04:50 UTC, Harmon758 requested changes
I think it should be safe to assume `User.id` exists, as in `__eq__`.

2020-12-30 04:50 UTC, Harmon758 commented on tweepy/models.py
> +            return hash(self.id)
Using `hash` is unnecessary here, since `User.id` is already an integer.
```suggestion
            return self.id
```

2020-12-31 00:59 UTC, Harmon758 requested changes

2020-12-31 00:59 UTC, Harmon758 commented on tweepy/models.py
> +            raise TypeError('unhashable type: {} (no id attribute)'.format(type(self)))
```suggestion
        return self.id
```

2020-12-31 03:25 UTC, Harmon758 approved these changes

2020-12-31 03:25 UTC, merged

2020-12-31 03:33 UTC, mef51 commented
Thanks!