Added support for `stringify_ids` param in followers_ids method
tweepy/tweepy pull request #1368
Opened 2020-05-16 16:29 UTC by rjh336

See [Twitter doc page](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids) for more details.

2020-05-16 23:02 UTC, MichaelCurrin commented
There's no benefit for this in Python. In JavaScript you need this param or id_str in general to prevent losing precision but Python handles the int fine.

Use `str(tweet.id)` if you really need string values.

2020-05-16 23:04 UTC, MichaelCurrin commented
The changes made look fine

2021-02-12 22:13 UTC, Harmon758 requested changes
There are conflicts that need to be resolved now.

2021-02-12 22:13 UTC, Harmon758 commented on docs/api.rst
> +.. method:: API.followers_ids(id/screen_name/user_id, [cursor], [stringify_ids])
```suggestion
.. method:: API.followers_ids(id/screen_name/user_id, [stringify_ids], \
                              [cursor])
```

2021-02-12 22:13 UTC, Harmon758 commented on docs/api.rst
> +   :param stringify_ids: Set to true to have ids returned as strings instead. Defaults to false.
```suggestion
   :param stringify_ids: Set to true to have IDs returned as strings instead. Defaults to false.
   :param cursor: |cursor|
```

2021-02-12 22:13 UTC, Harmon758 commented on tweepy/api.py
> +            :allowed_param: 'id', 'user_id', 'screen_name', 'cursor', 'stringify_ids', 'count'
```suggestion
            :allowed_param: 'id', 'user_id', 'screen_name', 'cursor',
                            'stringify_ids', 'count'
```

2021-02-12 22:13 UTC, Harmon758 commented on tweepy/api.py
> +            allowed_param=['id', 'user_id', 'screen_name', 'cursor', 'stringify_ids', 'count']
```suggestion
            allowed_param=['id', 'user_id', 'screen_name', 'cursor',
                           'stringify_ids', 'count']
```

2021-04-07 17:02 UTC, Harmon758 commented
Resolved by https://github.com/tweepy/tweepy/commit/c490027e936c3a0a1a62cfa3cb321358414b3b93

2021-04-07 17:02 UTC, closed without merging