Fixes #1412
tweepy/tweepy pull request #1413
Opened 2020-08-10 10:44 UTC by fkropfhamer

Fixes #1412 by transforming file argument to bytes and passing to `imghdr.what` in `api.media_upload`

2020-09-28 16:09 UTC, 5ym commented
This is an important feature. Please release as soon as possible.

2020-09-28 16:46 UTC, 5ym commented
I get the same error with update_profile_banner.

![image](https://user-images.githubusercontent.com/13718335/94461734-7c5cbd80-01f5-11eb-845b-dcaededd222d.png)

2020-10-06 22:25 UTC, SimoneABNto commented
Same problem here

2020-11-06 13:11 UTC, leoffx commented
I had the same problem, and this branch fixed it for me! I hope this get merged soon, thank you!

2020-12-22 16:08 UTC, Harmon758 requested changes
This will error with `AttributeError: 'NoneType' object has no attribute 'read'` when `file` is not passed.

2020-12-22 17:16 UTC, Harmon758 requested changes

2020-12-22 17:16 UTC, Harmon758 commented on tweepy/api.py
```suggestion

        h = None
        if f is not None:
            location = f.tell()
            h = f.read(32)
            f.seek(location)
```

2020-12-22 17:34 UTC, Harmon758 approved these changes

2020-12-22 17:34 UTC, merged