fixed Issue 106
tweepy/tweepy pull request #1444
Opened 2020-10-02 19:41 UTC by brett-schneider

2020-10-02 19:43 UTC, brett-schneider commented
also added endpoint
[get-lists-ownerships](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/api-reference/get-lists-ownerships)

2020-12-25 07:05 UTC, Harmon758 requested changes

2020-12-25 07:05 UTC, Harmon758 commented on tweepy/api.py
> +
This should be part of a separate pull request, which should also add documentation for the method.

2020-12-25 07:05 UTC, Harmon758 commented on tweepy/api.py
> +                           'cursor', 'count']
This should also be part of another separate pull request, which should also add documentation for the new allowed parameter.

2020-12-25 07:05 UTC, Harmon758 commented on tweepy/models.py
> +        return self._api.lists_ownerships(user_id=self.id,
This should be part of the separate pull request that adds `API.lists_ownerships`.

2020-12-26 00:50 UTC, Harmon758 commented
Since this is the last PR I want to include for v3.10, I've gone ahead and removed the extraneous changes myself.
Feel free to open separate PRs for them.

2020-12-26 00:50 UTC, Harmon758 approved these changes

2020-12-26 00:51 UTC, merged