Remove async from filter and sample functions
tweepy/tweepy pull request #1584
Opened 2021-05-12 19:32 UTC by crunis

I think `filter` and `sample` functions shouldn't be `async` since they only return a task.

This way, we can directly execute the task:
```
await AsyncStream.filter()
```

If the `async` is left, it forces us to use an initial `await` to retrieve the task and then another `await` to execute it:
```
task = await AsyncStream.filter()
await task
```

2021-05-12 22:39 UTC, Harmon758 requested changes
Awaiting the [`asyncio.Task`](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task) is not necessary for it to run. It simply blocks until the Task is done. `await AsyncStream.filter()` already "directly executes" the task (assuming `AsyncStream` is actually an instance of `AsyncStream` here), as does `task = await AsyncStream.filter()`. `await task` simply blocks until the stream disconnects.

However, it's true that `AsyncStream.filter` and `AsyncStream.sample` don't need to be coroutines now, with https://github.com/tweepy/tweepy/commit/59872045009ffb4bb5f42af3938c6a5722fc4f4c, and changing them to not be coroutines would simplify their usage.

2021-05-12 22:39 UTC, Harmon758 commented on tweepy/asynchronous/streaming.py
>          """|coroutine|
This documentation indicating it's a coroutine needs to be removed.

2021-05-12 22:39 UTC, Harmon758 commented on tweepy/asynchronous/streaming.py
>          Sample realtime Tweets
```suggestion
        """Sample realtime Tweets
```

2021-05-13 08:34 UTC, crunis commented
Updated the documentation of filter and sample functions.

2021-05-13 09:21 UTC, Harmon758 approved these changes

2021-05-13 09:22 UTC, merged