Fixes stream timeouts on shotty connections
tweepy/tweepy pull request #675
Opened 2015-11-22 14:30 UTC by ccphillippi

Now catches ConnectionError, ReadTimeOutError, ProtocolError in addition to Timeout, ssl.SSLError during stream, handling as a timeout to resolve #617 per suggestion by @jcapde87

2016-02-01 17:50 UTC, ZeerakW commented
Is there any reason this hasn't been pulled?

2016-10-10 20:18 UTC, sam-s commented
this seems to be an improvement, but not a complete fix.
I still see 
```
TweepError: Failed to send request: ('Connection aborted.', error(54, 'Connection reset by peer'))
```

2020-07-08 06:35 UTC, joshthecoder commented
Closing this is pretty old now and not active

2021-01-05 08:41 UTC, Harmon758 commented
This is not stale.

2021-01-05 09:16 UTC, Harmon758 requested changes
I think consistently including an explicit reference to the corresponding library/package for each exception handled is better here, so that it's clearer which exceptions are being handled.

Also, the StreamListener method should probably be updated to indicate that it could be called due to connection errors as well as timeouts.

2021-01-05 09:16 UTC, Harmon758 commented on tweepy/streaming.py
> +            except (Timeout, ssl.SSLError, ConnectionError, ReadTimeoutError, ProtocolError) as exc:
```suggestion
            except (requests.ConnectionError, requests.Timeout, ssl.SSLError,
                    urllib3.exceptions.ReadTimeoutError,
                    urllib3.exceptions.ProtocolError) as exc:
```

2021-01-05 09:16 UTC, Harmon758 commented on tweepy/streaming.py
> +from requests.packages.urllib3.exceptions import ReadTimeoutError, ProtocolError
```suggestion
import urllib3
```

2021-01-19 09:46 UTC, Harmon758 commented
I've gone ahead and resolved this with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f (and https://github.com/tweepy/tweepy/commit/8f622971f2a36f49ad54b70cf4f98464487a4716).

2021-01-19 09:46 UTC, closed without merging

2021-03-31 14:34 UTC, dheeman00 commented
Not sure why this thread is close. But this issue still exists with the tweepy library but there is not any proper solution to handle this issue.

2021-03-31 14:52 UTC, Harmon758 commented
As the closing comment says, this was resolved with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f.
Feel free to create a new issue if you can still reproduce it with the latest development version on the master branch.

2021-03-31 16:40 UTC, dheeman00 commented
@Harmon758 Thanks for your response. I am trying to extract the follower IDs for the top Twitter followers. But I encounter this error if there is any issue with the connection (either from the firewall or server-side). But can the code be modified in a way where the extraction starts from the point it stopped? I am not willing to crawl from the beginning of the list.

2021-03-31 17:22 UTC, Harmon758 commented
That doesn't seem like it has anything to do with this PR, which specifically involves connection issues while streaming.
Feel free to create a discussion with your relevant code if you have questions about using Tweepy.
Without seeing the actual code (and traceback), it's not really possible to tell you how it could be modified to handle your issue.

2021-03-31 17:37 UTC, dheeman00 commented
@Harmon758 I will go ahead and create a new thread for my issue.