Allow int or str IDs as streaming arguments
tweepy/tweepy pull request #830
Opened 2017-01-03 02:07 UTC by fitnr

Fix for #829. The str.join method raises a `ValueError` for `int`s.

2017-01-03 04:17 UTC, dannguyen commented
Thanks @fitnr. I'm only just getting acquainted with using the Streaming API vs Tweepy so I know there are other dependencies and conventions to consider, so this is for future discussion: it might be worthwhile **to throw a warning** when a user passes in a string.

Right now, the behavior -- and I'm assuming this is unintended -- is to silently fail when a string value is passed into the `follow` argument/parameter. But because the `follow` parameter, according to Twitter's API spec, *only* accepts user IDs: 

https://dev.twitter.com/streaming/overview/request-parameters#follow

> A comma-separated list of user IDs, indicating the users whose Tweets should be delivered on the stream. 

In other words, it is never the case that the Twitter API will accept `follow=["ev"]`. Shouldn't the user be warned that what they are trying will *always* turn up nothing? 

In fact, I'd almost argue that it's better for `filter` to _throw an error_. Consider the uncommon case in which a user's **screen name** is entirely made up of numbers. Such as Twitter user [@101](https://twitter.com/101), whose __user_id__ is actually [3781411](http://gettwitterid.com/?user_name=101&submit=GET+USER+ID).

What behavior should the user expect with the following invocation?

       mystream.filter(follow=['101'])


Forcing the API of `filter` to accept *only* integers provides at least an implication of what the `follow` parameter is limited to:

       mystream.filter(follow=[101])

2017-01-03 15:22 UTC, fitnr commented
I don't think changing signature of the `stream.filter` function to now throw warnings or errors when sequences of `str`s are passed is a friendly choice. Since a Twitter ID may, for good reason, be stored either as an `int` or a `str`, I say let the [function accept either](https://docs.python.org/3.5/glossary.html#term-duck-typing), and throw an error if Twitter complains. Designing guard rails or trying to police a certain kind of behvaior seems unnecessary in a library that  tracks a complicated and ever-changing API.

To answer your question about this:
```python
mystream.filter(follow=['101'])
````
I would expect that will produce a stream that follows the user with `user_id == 101`. I would base that on reading the [API spec on streaming](https://dev.twitter.com/streaming/overview/request-parameters#follow). It should also be documented in the Tweepy docs (which are currently a little garbled on the streaming API, but that's another issue).

2020-12-30 03:13 UTC, Harmon758 requested changes

2020-12-30 03:13 UTC, Harmon758 commented on tweepy/streaming.py
> +            self.body['follow'] = u','.join(str(f) for f in follow).encode(encoding)
```suggestion
            self.body['follow'] = u','.join(map(str, follow)).encode(encoding)
```

2020-12-30 03:13 UTC, Harmon758 commented on tweepy/streaming.py
> +            self.body['track'] = u','.join(str(f) for f in track).encode(encoding)
```suggestion
            self.body['track'] = u','.join(map(str, track)).encode(encoding)
```

2021-02-21 21:46 UTC, Harmon758 approved these changes

2021-02-21 21:46 UTC, merged