Tidied up Streaming.py
tweepy/tweepy pull request #895
Opened 2017-06-11 02:41 UTC by Kevin-Gillanders

Gave variables more descriptive names. made file PEP8 compliant

2017-06-19 16:04 UTC, wjt commented on examples/streaming.py
> +    myStream = Stream(auth = api.auth, listener = myStreamListener)
If you're aiming to be PEP 8-compliant, there should not be spaces around the `=`s for keyword parameters. From the [Other Recommendations](https://www.python.org/dev/peps/pep-0008/#other-recommendations) section:

> Don't use spaces around the = sign when used to indicate a keyword argument or a default parameter value.

2017-06-19 16:18 UTC, fitnr commented on examples/streaming.py
> +    myStream = Stream(auth = api.auth, listener = myStreamListener)
Also see [the naming conventions section](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) for instances:

> lowercase with words separated by underscores as necessary to improve readability.

2021-01-24 11:05 UTC, Harmon758 requested changes
Using `API` isn't necessary for streaming and doesn't need to be added here.

2021-01-24 11:05 UTC, Harmon758 commented on examples/streaming.py
> +    myStream = Stream(auth = api.auth, listener = myStreamListener)
As noted:
```suggestion
    stream = Stream(auth=api.auth, listener=stream_listener)
```

2021-01-24 11:05 UTC, Harmon758 commented on examples/streaming.py
> +    # python. The track parameter is an array of search terms to stream.
```suggestion
    # "python". The track parameter is a list of search terms to stream.
```

2021-01-24 11:05 UTC, Harmon758 commented on examples/streaming.py
> +    myStream.filter(track = ['python'])
```suggestion
    stream.filter(track=['python'])
```

2021-04-12 19:45 UTC, Harmon758 commented
This is stale now, with https://github.com/tweepy/tweepy/commit/e3e1d062377a5833b16e8ac8976a56ac57fac8a2.

2021-04-12 19:45 UTC, closed without merging